[package]
name = "zerochain-proofs"
version = "0.1.0"
authors = ["osuke <dish230@gmail.com>"]
edition = "2018"

[dependencies]
pairing = { git = "https://github.com/LayerXcom/librustzcash", branch = "zero-chain" }
bellman = { git = "https://github.com/LayerXcom/librustzcash", branch = "zero-chain" }
scrypto = { package = "sapling-crypto", git = "https://github.com/LayerXcom/librustzcash", branch = "zero-chain" }
rand = "0.4"
byteorder = "1"
bellman-verifier = { path = "../bellman-verifier" }
zpairing = { package = "zerochain-pairing", path = "../pairing"}
zprimitives = { package = "zerochain-primitives", path = "../primitives" }
polkadot-rs = { git = "https://github.com/LayerXcom/polkadot.rs" }
hex-literal = '0.1'
hex = "0.3.2"
keys = { path = "../keys"}
zjubjub = { package = "jubjub", path = "../jubjub" }
zerochain-runtime = { path = "../../runtime" }
lazy_static = "1.3.0"

[dependencies.primitives]
git = 'https://github.com/osuketh/substrate.git'
package = 'substrate-primitives'
branch = "patch-zerochain"

[dependencies.runtime-primitives]
git = 'https://github.com/osuketh/substrate.git'
package = 'sr-primitives'
branch = "patch-zerochain"

[dependencies.blake2-rfc]
git = "https://github.com/gtank/blake2-rfc"
rev = "7a5b5fc99ae483a0043db7547fb79a6fa44b88a9"

[dependencies.parity-codec]
features = ['derive']
version = '3.2'
